[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.build]
cmds = [
  "cp ../../../prisma/schema.prisma ./schema.prisma",
  "npm install",
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npm start"
